# Jirax Configuration File Example
# Copy this file to config.toml and fill in your credentials

[jira]
# Your Jira instance URL (e.g., https://your-company.atlassian.net)
server = ""
# Authentication type - either "basic" or "bearer"
auth_type = "basic"
# Whether to verify SSL certificates (set to false for self-signed certificates)
verify_ssl = true
# Connection timeout in seconds (increase for slow connections)
timeout = 60

# For Basic Authentication (default):
# Your personal access token (PAT)
token = ""
# Your Atlassian email address
email = ""

# For Bearer Token Authentication:
# Uncomment these and comment the above
# auth_type = "bearer"
# token = "your-bearer-token"
# login = "your-jira-username"  # Only if your Jira instance requires a username with bearer token
# email is not required for bearer auth

[extraction]
# Default project to extract from if no project is specified
default_project = ""
# Default max results to fetch
max_results = 1000
# Default output directory for extractions
output_directory = "./exports"

[display]
# Show preview before exporting
preview = true
# Number of rows to show in preview
preview_rows = 5

[columns]
# Column names for CSV export
# These are the column names that will be used when exporting issues to CSV
# You can customize these to change the column headers in your exported CSV file
Key = "Key"
Summary = "Summary"
Issue_Type = "Issue Type"
Status = "Status"
Priority = "Priority"
Assignee = "Assignee"
Reporter = "Reporter"
Resolution = "Resolution"
Updated = "Updated"
Sprint = "Sprint"
Epic_Key = "Epic Key"
Epic_Name = "Epic Name"
Labels = "Labels"
Extract_Date = "Extract Date"
