# Jirax Configuration File Example
# Copy this file to config.toml and fill in your credentials

[jira]
# Your Jira instance URL (e.g., https://your-company.atlassian.net)
server = ""
# Authentication type - either "basic" or "bearer"
auth_type = "basic"

# For Basic Authentication (default):
# Your personal access token (PAT)
token = ""
# Your Atlassian email address
email = ""

# For Bearer Token Authentication:
# Uncomment these and comment the above
# auth_type = "bearer"
# token = "your-bearer-token"
# login = "your-jira-username"  # Only if your Jira instance requires a username with bearer token
# email is not required for bearer auth

[extraction]
# Default project to extract from if no project is specified
default_project = ""
# Default max results to fetch
max_results = 1000
# Default output directory for extractions
output_directory = "./exports"

[display]
# Show preview before exporting
preview = true
# Number of rows to show in preview
preview_rows = 5
